version: "3"
services:
  ssl_generator:
    build:
      context: .
      dockerfile: ssl-generator.Dockerfile
    volumes:
      - ./certs:/certs  # Mount the certs directory for storing generated SSL certificates
  nginx:
    image: nginx:latest
    container_name: "proxy-nginx"
    depends_on:
      - bot_project
      - mvc_project
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs  # Mount the certs directory for SSL certificates
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
  mvc_project:
    build:
      context: . 
      dockerfile: mvc.Dockerfile
    ports:
      - 8080:80  # Port exposed by your MVC application
  bot_project:
    build:
      context: .
      dockerfile: bot.Dockerfile  
    ports:
      - 3978:80  # Port exposed by your bot application
    